name: HvZPlugin
version: 0.1.1
main: com.egsrit.hvz.HvZPlugin
api-version: 1.13
commands:
    hvz:
        description: Add a player to the humans or zombies
        usage: /<command> [human|zombie] [specialType]
depend: [ArmorEquipEvent]